// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNwzz1RIEG-NiO6yTZL4PVeebHrda21hE',
    appId: '1:965483289021:web:559d3b836c0d64de639ad4',
    messagingSenderId: '965483289021',
    projectId: 'notification-ea23a',
    authDomain: 'notification-ea23a.firebaseapp.com',
    databaseURL: 'https://notification-ea23a-default-rtdb.firebaseio.com',
    storageBucket: 'notification-ea23a.appspot.com',
    measurementId: 'G-1EES2XND5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGrJeJF31OR0-58sl8EY3iLdwYi4m6u10',
    appId: '1:965483289021:android:7bfb9093cdfdbcb1639ad4',
    messagingSenderId: '965483289021',
    projectId: 'notification-ea23a',
    databaseURL: 'https://notification-ea23a-default-rtdb.firebaseio.com',
    storageBucket: 'notification-ea23a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM13ApAgmORIlpzg2mcCo_l96EHp6V3d8',
    appId: '1:965483289021:ios:876cce2ff5caca46639ad4',
    messagingSenderId: '965483289021',
    projectId: 'notification-ea23a',
    databaseURL: 'https://notification-ea23a-default-rtdb.firebaseio.com',
    storageBucket: 'notification-ea23a.appspot.com',
    iosBundleId: 'com.example.testNotification',
  );
}
